-- Assistente Clinico | protocolos internos do hospital

SET client_encoding = 'UTF8';

TRUNCATE knowledge.protocolos RESTART IDENTITY CASCADE;

-- 25 protocolos
INSERT INTO knowledge.protocolos (id, titulo, especialidade, resumo) VALUES
  ('PROT-ALTA-24', 'Alta hospitalar segura e reconciliacao medicamentosa', 'clinica medica', 'Conferencia de pendencias, reconciliacao de medicamentos e orientacao de retorno.'),
  ('PROT-ANTICOAG-05', 'Anticoagulacao oral: inicio, monitorizacao e reversao', 'hematologia', 'Escolha do anticoagulante, alvo de INR e conduta no sangramento.'),
  ('PROT-ASMA-08', 'Crise asmatica no pronto-socorro', 'pneumologia', 'Classificacao da gravidade, tratamento inicial e criterios de alta.'),
  ('PROT-ATB-13', 'Uso racional de antimicrobianos', 'clinica medica', 'Regras institucionais de prescricao, descalonamento e tempo de tratamento.'),
  ('PROT-AVC-15', 'Acidente vascular cerebral isquemico agudo', 'neurologia', 'Codigo AVC, janela terapeutica e criterios de trombolise.'),
  ('PROT-CAD-18', 'Cetoacidose diabetica', 'endocrinologia', 'Criterios diagnosticos, hidratacao, insulina e reposicao de potassio.'),
  ('PROT-CONV-16', 'Crise convulsiva e estado de mal epileptico', 'neurologia', 'Sequencia temporal do tratamento e investigacao da causa.'),
  ('PROT-DM-17', 'Diabetes tipo 2: manejo hospitalar e ambulatorial', 'endocrinologia', 'Metas glicemicas, insulinizacao e ajuste de metformina.'),
  ('PROT-DOR-12', 'Analgesia no pronto-socorro', 'clinica medica', 'Escada analgesica institucional e cuidados com AINE e opioide.'),
  ('PROT-DPOC-07', 'Exacerbacao de doenca pulmonar obstrutiva cronica', 'pneumologia', 'Broncodilatacao, corticoide sistemico, indicacao de antibiotico e de ventilacao nao invasiva.'),
  ('PROT-FA-03', 'Fibrilacao atrial de inicio recente', 'cardiologia', 'Controle de frequencia, decisao sobre cardioversao e indicacao de anticoagulacao.'),
  ('PROT-HAS-04', 'Emergencia e urgencia hipertensiva', 'cardiologia', 'Diferenciacao entre urgencia e emergencia hipertensiva e metas de reducao pressorica.'),
  ('PROT-HDA-22', 'Hemorragia digestiva alta', 'gastroenterologia', 'Estabilizacao, inibidor de bomba de protons e janela para endoscopia.'),
  ('PROT-IA-25', 'Uso de assistente de inteligencia artificial no apoio a decisao clinica', 'governanca', 'Limites de atuacao, obrigatoriedade de validacao humana e regras de auditoria do assistente virtual do hospital.'),
  ('PROT-ICA-02', 'Insuficiencia cardiaca descompensada', 'cardiologia', 'Manejo da descompensacao aguda, do perfil hemodinamico a titulacao de diureticos.'),
  ('PROT-ITU-11', 'Infeccao do trato urinario no adulto', 'clinica medica', 'Diferenciacao entre cistite, pielonefrite e bacteriuria assintomatica.'),
  ('PROT-K-21', 'Disturbios do potassio', 'nefrologia', 'Conduta na hipercalemia e na hipocalemia, com limiares de acao imediata.'),
  ('PROT-LRA-20', 'Lesao renal aguda no paciente internado', 'nefrologia', 'Criterios KDIGO, suspensao de nefrotoxicos e indicacao de dialise.'),
  ('PROT-PNM-06', 'Pneumonia adquirida na comunidade', 'pneumologia', 'Estratificacao pelo CURB-65, escolha empirica de antibiotico e criterios de internacao.'),
  ('PROT-QUEDA-14', 'Prevencao de quedas no paciente internado', 'enfermagem', 'Avaliacao de risco, medidas preventivas e conduta pos-queda.'),
  ('PROT-SCA-01', 'Dor toracica e sindrome coronariana aguda', 'cardiologia', 'Fluxo de atendimento da dor toracica no pronto-socorro, da triagem a definicao de conduta invasiva ou conservadora.'),
  ('PROT-SEPSE-10', 'Sepse e choque septico', 'clinica medica', 'Pacote da primeira hora, coleta de culturas e ressuscitacao volemica.'),
  ('PROT-TEP-09', 'Suspeita de tromboembolismo pulmonar', 'pneumologia', 'Probabilidade pre-teste, uso do D-dimero e indicacao de angiotomografia.'),
  ('PROT-TIRE-19', 'Hipotireoidismo: diagnostico e reposicao', 'endocrinologia', 'Interpretacao do TSH, dose de levotiroxina e intervalo de controle.'),
  ('PROT-TRANSF-23', 'Indicacao transfusional de concentrado de hemacias', 'hematologia', 'Gatilhos transfusionais institucionais e registro obrigatorio.');

-- 109 trechos
INSERT INTO knowledge.trechos (protocolo_id, ordem, secao, texto) VALUES
  ('PROT-ALTA-24', 1, 'Pendencias que bloqueiam a alta', 'Nenhum paciente recebe alta com exame solicitado e sem resultado liberado, ou com resultado critico nao avaliado. O sistema bloqueia a alta ate a pendencia ser resolvida ou justificada.'),
  ('PROT-ALTA-24', 2, 'Reconciliacao medicamentosa', 'Comparar a lista de medicamentos de uso domiciliar com a prescricao de alta e justificar cada inclusao, suspensao ou troca de dose.'),
  ('PROT-ALTA-24', 3, 'Alergias', 'Reconferir as alergias registradas contra a prescricao de alta. Divergencia impede a liberacao.'),
  ('PROT-ALTA-24', 4, 'Orientacao de retorno', 'Entregar por escrito os sinais de alarme e a data da reavaliacao. Registrar a entrega em prontuario.'),
  ('PROT-ANTICOAG-05', 1, 'Escolha do agente', 'Anticoagulantes diretos sao a primeira escolha na fibrilacao atrial nao valvar e no tromboembolismo venoso. Cumarinico permanece indicado em protese valvar mecanica, estenose mitral reumatica e clearance de creatinina abaixo de 15 mL/min.'),
  ('PROT-ANTICOAG-05', 2, 'Alvo terapeutico do cumarinico', 'INR alvo entre 2,0 e 3,0 na maioria das indicacoes, e entre 2,5 e 3,5 em protese mecanica mitral. Controle semanal ate duas medidas consecutivas na faixa, depois mensal.'),
  ('PROT-ANTICOAG-05', 3, 'Conduta no INR elevado', 'INR entre 5,0 e 9,0 sem sangramento: suspender uma a duas doses e reavaliar em 24 horas. INR acima de 9,0 ou qualquer sangramento maior: suspender o cumarinico, administrar vitamina K e avaliar complexo protrombinico com o hematologista.'),
  ('PROT-ANTICOAG-05', 4, 'Interacoes de vigilancia obrigatoria', 'Macrolideos, quinolonas, azoicos, amiodarona e anti-inflamatorios nao esteroidais alteram de forma relevante o efeito do cumarinico. A introducao de qualquer um deles em paciente anticoagulado obriga controle de INR em 48 a 72 horas.'),
  ('PROT-ANTICOAG-05', 5, 'Antiagregante associado', 'A associacao de antiagregante com anticoagulante so se justifica em indicacao formal documentada em prontuario, pelo menor tempo possivel, e exige protetor gastrico concomitante.'),
  ('PROT-ASMA-08', 1, 'Classificacao', 'Crise grave: incapacidade de completar frases, frequencia respiratoria acima de 30, uso de musculatura acessoria ou saturacao abaixo de 90 por cento. Torax silencioso, bradicardia ou confusao indicam crise potencialmente fatal.'),
  ('PROT-ASMA-08', 2, 'Tratamento inicial', 'Salbutamol inalatorio a cada 20 minutos na primeira hora, corticoide sistemico na primeira hora e oxigenio para manter saturacao entre 93 e 95 por cento.'),
  ('PROT-ASMA-08', 3, 'Reavaliacao', 'Reavaliar em uma hora. Melhora sustentada por mais de uma hora permite alta. Ausencia de resposta indica internacao e avaliacao de sulfato de magnesio.'),
  ('PROT-ASMA-08', 4, 'Alta e seguimento', 'Alta somente com corticoide oral por cinco dias, tecnica inalatoria revisada e consulta ambulatorial agendada em ate sete dias.'),
  ('PROT-ATB-13', 1, 'Indicacao', 'Toda prescricao de antimicrobiano exige hipotese diagnostica registrada em prontuario. Antibiotico prescrito por febre isolada, sem foco definido, deve ser reavaliado em 24 horas.'),
  ('PROT-ATB-13', 2, 'Descalonamento', 'Reavaliar o espectro em 48 a 72 horas a luz das culturas. O descalonamento e obrigatorio sempre que o agente for identificado e o perfil de sensibilidade permitir.'),
  ('PROT-ATB-13', 3, 'Tempo de tratamento', 'Cursos curtos sao a regra: cinco a sete dias na maioria das infeccoes comunitarias. Prolongar exige justificativa registrada.'),
  ('PROT-AVC-15', 1, 'Ativacao do codigo AVC', 'Deficit neurologico focal de inicio subito aciona o codigo AVC. Registrar o horario do ultimo momento em que o paciente foi visto bem: e esse horario, e nao o da chegada, que define a janela terapeutica.'),
  ('PROT-AVC-15', 2, 'Tomografia', 'Tomografia de cranio sem contraste em ate 25 minutos da chegada, laudada em ate 45 minutos. O objetivo primario e excluir hemorragia.'),
  ('PROT-AVC-15', 3, 'Trombolise endovenosa', 'Indicada em ate 4,5 horas do inicio dos sintomas, na ausencia de contraindicacao. Sao contraindicacoes absolutas: hemorragia na tomografia, INR acima de 1,7, plaquetas abaixo de 100 mil e uso de anticoagulante direto nas ultimas 48 horas.'),
  ('PROT-AVC-15', 4, 'Controle pressorico', 'Antes da trombolise, manter pressao abaixo de 185 por 110 mmHg. Sem indicacao de trombolise, tratar apenas se a pressao ultrapassar 220 por 120 mmHg, pela dependencia do fluxo colateral.'),
  ('PROT-AVC-15', 5, 'Exames obrigatorios antes da trombolise', 'Glicemia capilar, INR, plaquetas e tomografia laudada. A ausencia de qualquer um desses resultados impede a liberacao do tromboliticos.'),
  ('PROT-CAD-18', 1, 'Diagnostico', 'Trinca de glicemia acima de 250 mg/dL, acidose metabolica com pH abaixo de 7,3 ou bicarbonato abaixo de 18, e cetonemia ou cetonuria.'),
  ('PROT-CAD-18', 2, 'Hidratacao', 'Cristaloide isotonico e a primeira medida, antes da insulina. A reposicao volemica sozinha ja reduz a glicemia de forma significativa.'),
  ('PROT-CAD-18', 3, 'Potassio antes da insulina', 'Nao iniciar insulina com potassio abaixo de 3,3 mEq/L: a insulina desloca potassio para o intracelular e pode precipitar arritmia fatal. Repor potassio primeiro.'),
  ('PROT-CAD-18', 4, 'Insulina', 'Infusao continua de insulina regular, com meta de queda de 50 a 75 mg/dL por hora. Quando a glicemia atingir 200 mg/dL, associar soro glicosado e manter a insulina ate a resolucao da acidose.');
INSERT INTO knowledge.trechos (protocolo_id, ordem, secao, texto) VALUES
  ('PROT-CAD-18', 5, 'Criterios de resolucao', 'Glicemia abaixo de 200 mg/dL somada a bicarbonato acima de 15, pH acima de 7,3 e anion gap normalizado.'),
  ('PROT-CONV-16', 1, 'Definicao', 'Crise com mais de cinco minutos de duracao, ou crises repetidas sem recuperacao da consciencia entre elas, caracteriza estado de mal epileptico.'),
  ('PROT-CONV-16', 2, 'Primeira linha', 'Benzodiazepinico endovenoso nos primeiros cinco minutos. Doses subterapeuticas sao a causa mais frequente de falha do tratamento inicial.'),
  ('PROT-CONV-16', 3, 'Segunda linha', 'Se a crise persistir apos 10 minutos, iniciar anticonvulsivante endovenoso de manutencao. Verificar interacao com anticoagulante em uso.'),
  ('PROT-CONV-16', 4, 'Investigacao', 'Glicemia capilar imediata em toda crise. Solicitar sodio, calcio, magnesio, funcao renal e tomografia de cranio na primeira crise ou em mudanca do padrao habitual.'),
  ('PROT-DM-17', 1, 'Metas', 'No paciente internado nao critico, manter glicemia entre 140 e 180 mg/dL. Metas mais rigorosas aumentam hipoglicemia sem beneficio. No ambulatorio, alvo de hemoglobina glicada abaixo de 7 por cento, individualizado pela idade e comorbidades.'),
  ('PROT-DM-17', 2, 'Metformina no hospital', 'Suspender metformina em instabilidade hemodinamica, lesao renal aguda, clearance abaixo de 30 mL/min e nas 48 horas que cercam exame com contraste iodado.'),
  ('PROT-DM-17', 3, 'Insulinizacao', 'Preferir esquema basal-bolus. Insulina apenas por escala de correcao, sem dose basal, e pratica desencorajada por gerar oscilacao glicemica.'),
  ('PROT-DM-17', 4, 'Hipoglicemia', 'Glicemia abaixo de 70 mg/dL exige tratamento imediato e revisao da prescricao. Abaixo de 50 mg/dL e evento critico e deve ser notificado.'),
  ('PROT-DM-17', 5, 'Betabloqueador associado', 'Betabloqueador mascara os sinais adrenergicos de hipoglicemia. Em diabetico em uso dessa classe, intensificar a monitorizacao glicemica e orientar o paciente.'),
  ('PROT-DOR-12', 1, 'Avaliacao', 'Registrar a intensidade da dor em escala de 0 a 10 na admissao e reavaliar 30 minutos apos cada intervencao.'),
  ('PROT-DOR-12', 2, 'Dor leve a moderada', 'Dipirona ou paracetamol como primeira linha. Verificar alergia registrada antes da prescricao: dipirona esta entre os alergenos mais frequentes nesta instituicao.'),
  ('PROT-DOR-12', 3, 'Restricoes ao anti-inflamatorio', 'Anti-inflamatorio nao esteroidal e contraindicado em doenca renal cronica, insuficiencia cardiaca, hemorragia digestiva previa e uso de anticoagulante. Nesses casos, escalonar direto para opioide fraco.'),
  ('PROT-DOR-12', 4, 'Opioide', 'Reservado para dor intensa. Prescrever sempre com antiemetico disponivel e monitorizacao de nivel de consciencia e frequencia respiratoria.'),
  ('PROT-DPOC-07', 1, 'Broncodilatacao', 'Beta-2 agonista de curta duracao inalatorio a cada 20 minutos na primeira hora, associado a anticolinergico. Reavaliar resposta antes de escalonar.'),
  ('PROT-DPOC-07', 2, 'Corticoide sistemico', 'Prednisona 40 mg por via oral por cinco dias. Cursos mais longos nao trazem beneficio adicional e aumentam efeitos adversos.'),
  ('PROT-DPOC-07', 3, 'Antibiotico', 'Indicado quando houver aumento do volume e da purulencia do escarro associado a piora da dispneia, ou quando o paciente necessitar de suporte ventilatorio. Escarro purulento isolado nao e indicacao suficiente.'),
  ('PROT-DPOC-07', 4, 'Oxigenio e ventilacao nao invasiva', 'Alvo de saturacao entre 88 e 92 por cento. Oxigenio em excesso agrava a retencao de gas carbonico. Acidose respiratoria com pH abaixo de 7,35 indica ventilacao nao invasiva precoce.'),
  ('PROT-FA-03', 1, 'Instabilidade hemodinamica', 'Hipotensao, angina, congestao pulmonar ou rebaixamento do nivel de consciencia indicam cardioversao eletrica sincronizada imediata, independentemente do tempo de arritmia.'),
  ('PROT-FA-03', 2, 'Controle de frequencia', 'Em paciente estavel, a meta e frequencia cardiaca abaixo de 110 bpm em repouso. Betabloqueador e a primeira escolha. Evitar betabloqueador em broncoespasmo ativo e verapamil em fracao de ejecao reduzida.'),
  ('PROT-FA-03', 3, 'Anticoagulacao', 'Calcular CHA2DS2-VASc. Escore igual ou maior que 2 em homens, ou 3 em mulheres, indica anticoagulacao oral por tempo indeterminado. A escolha entre cumarinico e anticoagulante direto considera funcao renal e adesao.'),
  ('PROT-FA-03', 4, 'Cardioversao e tempo de arritmia', 'Arritmia com mais de 48 horas de duracao, ou de tempo indeterminado, exige ecocardiograma transesofagico ou tres semanas de anticoagulacao plena antes da cardioversao eletiva.'),
  ('PROT-HAS-04', 1, 'Definicao', 'Emergencia hipertensiva e a elevacao pressorica com lesao aguda de orgao-alvo (encefalopatia, edema agudo de pulmao, dissecao de aorta, sindrome coronariana, lesao renal aguda). Sem lesao de orgao-alvo, trata-se de urgencia hipertensiva.'),
  ('PROT-HAS-04', 2, 'Metas de reducao', 'Na emergencia, reduzir a pressao arterial media em no maximo 25 por cento na primeira hora, com anti-hipertensivo endovenoso titulavel. Reducao mais rapida provoca hipoperfusao cerebral, coronariana e renal.'),
  ('PROT-HAS-04', 3, 'Urgencia hipertensiva', 'Na urgencia, a reducao deve ocorrer em 24 a 48 horas com medicacao oral. O uso de nifedipino sublingual esta proscrito nesta instituicao pelo risco de queda pressorica abrupta e imprevisivel.');
INSERT INTO knowledge.trechos (protocolo_id, ordem, secao, texto) VALUES
  ('PROT-HAS-04', 4, 'Investigacao minima', 'Solicitar ECG, creatinina, potassio, sodio e urina tipo 1 em todo episodio atendido no pronto-socorro.'),
  ('PROT-HDA-22', 1, 'Estabilizacao', 'Dois acessos calibrosos, reposicao volemica e tipagem sanguinea. Meta transfusional restritiva: hemoglobina alvo de 7 g/dL, exceto em coronariopatia, quando o alvo sobe para 8 g/dL.'),
  ('PROT-HDA-22', 2, 'Inibidor de bomba de protons', 'Iniciar por via endovenosa em bolus seguido de infusao continua antes mesmo da endoscopia.'),
  ('PROT-HDA-22', 3, 'Endoscopia', 'Realizar em ate 24 horas da admissao; em instabilidade hemodinamica persistente, em ate 12 horas.'),
  ('PROT-HDA-22', 4, 'Antitromboticos', 'Suspender antiagregante e anticoagulante e discutir a reversao com o hematologista. O reinicio depende do risco trombotico individual e deve ser decidido em conjunto.'),
  ('PROT-IA-25', 1, 'Natureza da saida do assistente', 'Toda saida do assistente virtual e uma sugestao de apoio a decisao. Nao constitui prescricao, laudo nem alta, e nao substitui a avaliacao do medico assistente, que permanece integralmente responsavel pela conduta.'),
  ('PROT-IA-25', 2, 'Vedacoes expressas', 'O assistente nao prescreve medicamento, nao define dose para paciente individual sem respaldo em protocolo vigente, nao emite laudo de exame de imagem e nao comunica diagnostico diretamente ao paciente ou a familiares.'),
  ('PROT-IA-25', 3, 'Obrigacao de citar a fonte', 'Toda afirmacao clinica do assistente deve indicar a origem: protocolo institucional com versao e secao, ou o registro do prontuario consultado. Afirmacao sem fonte verificavel deve ser recusada antes de chegar ao medico.'),
  ('PROT-IA-25', 4, 'Escopo de dados', 'O assistente acessa exclusivamente dados do paciente sob cuidado do profissional que consulta, em modo somente leitura. Nome, CPF e demais identificadores diretos nao sao enviados ao modelo de linguagem.'),
  ('PROT-IA-25', 5, 'Auditoria', 'Toda consulta e registrada com identificacao do profissional, pergunta, ferramentas acionadas, fontes citadas e resposta entregue. O registro fica disponivel para a Comissao de Etica pelo prazo definido em politica institucional.'),
  ('PROT-IA-25', 6, 'Alertas de seguranca', 'O assistente deve emitir alerta sempre que identificar exame pendente relevante, conflito entre prescricao e alergia registrada, interacao medicamentosa grave ou resultado laboratorial em faixa critica.'),
  ('PROT-ICA-02', 1, 'Classificacao do perfil', 'Classificar o paciente em quente-umido, frio-umido, quente-seco ou frio-seco na primeira hora. A maioria das descompensacoes e do perfil quente-umido e responde a diuretico endovenoso isolado.'),
  ('PROT-ICA-02', 2, 'Diuretico endovenoso', 'Furosemida endovenosa em dose equivalente ao dobro da dose oral domiciliar, administrada em bolus. Reavaliar diurese e peso a cada 12 horas. Ausencia de resposta em 6 horas indica dobrar a dose ou considerar infusao continua.'),
  ('PROT-ICA-02', 3, 'Monitorizacao laboratorial', 'Dosar creatinina, ureia, sodio e potassio na admissao e a cada 24 horas enquanto houver diuretico endovenoso. Elevacao de creatinina acima de 0,3 mg/dL em 48 horas caracteriza sindrome cardiorrenal e exige reavaliacao da estrategia.'),
  ('PROT-ICA-02', 4, 'BNP e diagnostico diferencial', 'BNP abaixo de 100 pg/mL torna a insuficiencia cardiaca improvavel como causa da dispneia. Valores acima de 400 pg/mL, em contexto clinico compativel, confirmam a descompensacao.'),
  ('PROT-ICA-02', 5, 'Terapia de manutencao', 'IECA ou BRA, betabloqueador e antagonista mineralocorticoide devem ser mantidos sempre que a pressao e a funcao renal permitirem. A suspensao do betabloqueador na descompensacao piora o prognostico e so se justifica em choque cardiogenico.'),
  ('PROT-ITU-11', 1, 'Bacteriuria assintomatica', 'Urocultura positiva sem sintomas nao deve ser tratada, exceto em gestantes e antes de procedimento urologico invasivo. Tratar bacteriuria assintomatica e uma das principais causas de uso desnecessario de antibiotico na instituicao.'),
  ('PROT-ITU-11', 2, 'Cistite nao complicada', 'Tratamento por tres a cinco dias com antimicrobiano de espectro estreito, guiado pelo perfil de sensibilidade local. Quinolona nao e primeira escolha em cistite nao complicada.'),
  ('PROT-ITU-11', 3, 'Pielonefrite', 'Febre, dor lombar e sinal de Giordano positivo indicam pielonefrite. Colher urocultura e hemocultura antes do antibiotico e tratar por sete a dez dias.'),
  ('PROT-ITU-11', 4, 'Reavaliacao com a cultura', 'Ajustar o antimicrobiano assim que a urocultura ficar disponivel, reduzindo o espectro sempre que possivel.'),
  ('PROT-K-21', 1, 'Hipercalemia: limiar de acao', 'Potassio acima de 6,0 mEq/L, ou qualquer valor com alteracao eletrocardiografica, exige tratamento imediato. Valor acima de 6,2 mEq/L e resultado critico e deve ser comunicado ao plantonista pelo laboratorio.'),
  ('PROT-K-21', 2, 'Sequencia do tratamento', 'Gluconato de calcio para estabilizar a membrana, insulina com glicose e beta-2 agonista para deslocamento intracelular, e diuretico ou dialise para remocao efetiva. Estabilizar nao e o mesmo que remover.'),
  ('PROT-K-21', 3, 'Medicamentos implicados', 'IECA, BRA, antagonista mineralocorticoide, anti-inflamatorio e heparina retem potassio. A associacao de IECA ou BRA com poupador de potassio exige controle laboratorial em sete dias.'),
  ('PROT-K-21', 4, 'Hipocalemia', 'Potassio abaixo de 3,5 mEq/L exige reposicao e dosagem de magnesio: hipomagnesemia nao corrigida torna a reposicao de potassio ineficaz. Abaixo de 2,8 mEq/L e resultado critico.'),
  ('PROT-LRA-20', 1, 'Definicao', 'Elevacao de creatinina igual ou maior que 0,3 mg/dL em 48 horas, aumento de 50 por cento em sete dias, ou diurese abaixo de 0,5 mL/kg/h por seis horas.');
INSERT INTO knowledge.trechos (protocolo_id, ordem, secao, texto) VALUES
  ('PROT-LRA-20', 2, 'Revisao da prescricao', 'Suspender ou ajustar todo nefrotoxico: anti-inflamatorio nao esteroidal, aminoglicosideo, vancomicina, contraste iodado e, temporariamente, IECA, BRA e metformina.'),
  ('PROT-LRA-20', 3, 'Investigacao', 'Diferenciar pre-renal, renal e pos-renal. Ultrassonografia de vias urinarias e obrigatoria para excluir obstrucao antes de assumir causa intrinseca.'),
  ('PROT-LRA-20', 4, 'Indicacao de dialise', 'Hipercalemia refrataria, acidose metabolica grave, hipervolemia refrataria a diuretico, uremia sintomatica ou intoxicacao dialisavel.'),
  ('PROT-PNM-06', 1, 'Estratificacao', 'Aplicar CURB-65 (confusao, ureia acima de 43 mg/dL, frequencia respiratoria igual ou maior que 30, pressao sistolica abaixo de 90 mmHg, idade igual ou maior que 65 anos). Escore 0 a 1 permite tratamento ambulatorial; 2 indica internacao; 3 ou mais indica avaliacao para terapia intensiva.'),
  ('PROT-PNM-06', 2, 'Exames na admissao', 'Radiografia de torax, hemograma, ureia, creatinina, sodio, potassio, PCR e saturacao de oxigenio. Hemoculturas e lactato quando houver criterio de gravidade.'),
  ('PROT-PNM-06', 3, 'Antibioticoterapia empirica', 'Paciente internado sem criterio de gravidade: betalactamico associado a macrolideo. Em alergia documentada a penicilina, substituir por quinolona respiratoria. A escolha final e do medico assistente e deve considerar a alergia registrada.'),
  ('PROT-PNM-06', 4, 'Duracao e reavaliacao', 'Duracao habitual de cinco a sete dias. Reavaliar em 48 a 72 horas: ausencia de melhora clinica obriga revisao diagnostica e discussao com a infectologia, e nao escalonamento automatico do antibiotico.'),
  ('PROT-PNM-06', 5, 'Criterios de alta', 'Estabilidade clinica por 24 horas, saturacao acima de 92 por cento em ar ambiente, aceitacao de via oral e ausencia de comorbidade descompensada.'),
  ('PROT-QUEDA-14', 1, 'Avaliacao de risco', 'Aplicar a escala de Morse na admissao e a cada mudanca de estado clinico. Pontuacao igual ou maior que 45 caracteriza alto risco e aciona sinalizacao no leito.'),
  ('PROT-QUEDA-14', 2, 'Medicamentos de risco', 'Benzodiazepinicos, opioides, anti-hipertensivos de inicio recente e hipoglicemiantes aumentam o risco de queda. A revisao da prescricao faz parte da prevencao.'),
  ('PROT-QUEDA-14', 3, 'Conduta pos-queda', 'Avaliacao medica imediata, exame neurologico e notificacao no sistema. Paciente anticoagulado que sofreu queda com trauma craniano exige tomografia de cranio mesmo sem sintomas.'),
  ('PROT-SCA-01', 1, 'Ativacao do protocolo', 'O protocolo e ativado para todo paciente adulto com dor toracica de caracteristica anginosa, equivalente anginoso (dispneia, sincope, epigastralgia) ou instabilidade hemodinamica sem causa evidente. A ativacao e responsabilidade do enfermeiro de triagem e independe de avaliacao medica previa.'),
  ('PROT-SCA-01', 2, 'Eletrocardiograma', 'ECG de 12 derivacoes em ate 10 minutos da chegada, laudado por medico em ate 10 minutos apos a realizacao. Supradesnivelamento de ST em duas derivacoes contiguas caracteriza IAMCSST e aciona a equipe de hemodinamica imediatamente, sem aguardar resultado de troponina.'),
  ('PROT-SCA-01', 3, 'Curva de troponina ultrassensivel', 'Colher troponina I ultrassensivel na admissao (T0) e repetir em 1 hora (T1). Valor de referencia institucional: ate 0,04 ng/mL. Delta absoluto maior que 0,02 ng/mL entre T0 e T1, ou valor isolado acima de 0,5 ng/mL, define lesao miocardica aguda e obriga internacao em unidade coronariana.'),
  ('PROT-SCA-01', 4, 'Estratificacao de risco', 'Aplicar o escore HEART. Escore de 0 a 3 com duas troponinas negativas permite alta com reavaliacao ambulatorial em 72 horas. Escore de 4 a 6 exige internacao para investigacao. Escore igual ou maior que 7 indica estrategia invasiva precoce em ate 24 horas.'),
  ('PROT-SCA-01', 5, 'Conduta farmacologica inicial', 'Na ausencia de contraindicacao: AAS 300 mg mastigavel na admissao, seguido de 100 mg ao dia. A dupla antiagregacao e a anticoagulacao plena so devem ser iniciadas apos avaliacao do cardiologista, por causa do risco hemorragico. Toda prescricao decorrente deste protocolo exige validacao do medico assistente.'),
  ('PROT-SCA-01', 6, 'Exames obrigatorios antes da alta', 'Nenhum paciente com dor toracica recebe alta sem ECG laudado e ao menos duas dosagens de troponina com intervalo minimo de uma hora. Se qualquer um desses itens estiver pendente, a alta fica bloqueada no sistema.'),
  ('PROT-SEPSE-10', 1, 'Rastreio', 'Aplicar qSOFA em todo paciente com suspeita de infeccao: frequencia respiratoria igual ou maior que 22, alteracao do nivel de consciencia e pressao sistolica igual ou menor que 100 mmHg. Dois criterios acionam o protocolo.'),
  ('PROT-SEPSE-10', 2, 'Pacote da primeira hora', 'Dentro de 60 minutos da suspeita: coletar lactato e duas hemoculturas de sitios distintos, iniciar antimicrobiano de amplo espectro e infundir 30 mL/kg de cristaloide se houver hipotensao ou lactato acima de 4 mmol/L.'),
  ('PROT-SEPSE-10', 3, 'Culturas antes do antibiotico', 'As hemoculturas devem ser coletadas antes da primeira dose, desde que isso nao atrase o antimicrobiano em mais de 45 minutos. Quando houver conflito, o antimicrobiano tem prioridade.'),
  ('PROT-SEPSE-10', 4, 'Lactato seriado', 'Repetir lactato em duas a quatro horas quando o inicial estiver acima de 2 mmol/L. Lactato que nao cai apos a ressuscitacao indica hipoperfusao persistente e necessidade de vasopressor.'),
  ('PROT-SEPSE-10', 5, 'Vasopressor', 'Iniciar noradrenalina se a pressao arterial media permanecer abaixo de 65 mmHg apos a reposicao volemica inicial, preferencialmente em acesso central, sem postergar o inicio pela puncao.'),
  ('PROT-TEP-09', 1, 'Probabilidade pre-teste', 'Aplicar o escore de Wells antes de qualquer exame. A conduta depende do resultado: probabilidade baixa ou intermediaria segue para D-dimero; probabilidade alta vai direto para angiotomografia.'),
  ('PROT-TEP-09', 2, 'D-dimero', 'Util apenas para excluir o diagnostico em probabilidade baixa ou intermediaria. Valor abaixo de 500 ng/mL nesse cenario afasta o diagnostico. D-dimero elevado nao confirma tromboembolismo e nao deve, sozinho, motivar anticoagulacao.'),
  ('PROT-TEP-09', 3, 'Angiotomografia', 'Exame confirmatorio. Verificar creatinina e alergia a contraste iodado antes da solicitacao. Alergia registrada exige discussao com a radiologia e considerar cintilografia de ventilacao e perfusao.');
INSERT INTO knowledge.trechos (protocolo_id, ordem, secao, texto) VALUES
  ('PROT-TEP-09', 4, 'Anticoagulacao empirica', 'Em probabilidade alta com exame confirmatorio nao disponivel de imediato, iniciar anticoagulacao plena apos avaliar risco hemorragico, com registro da justificativa em prontuario.'),
  ('PROT-TIRE-19', 1, 'Diagnostico', 'TSH elevado com T4 livre baixo confirma hipotireoidismo primario. TSH elevado com T4 livre normal caracteriza forma subclinica, cuja indicacao de tratamento depende do valor e do contexto clinico.'),
  ('PROT-TIRE-19', 2, 'Reposicao', 'Levotiroxina em jejum, 30 a 60 minutos antes do cafe. Iniciar com dose reduzida em idosos e em coronariopatas para nao precipitar angina.'),
  ('PROT-TIRE-19', 3, 'Controle', 'Reavaliar TSH seis a oito semanas apos o inicio ou apos qualquer ajuste de dose. Controles mais precoces refletem estado transitorio e induzem ajustes indevidos.'),
  ('PROT-TIRE-19', 4, 'Interferentes na absorcao', 'Carbonato de calcio, sulfato ferroso e inibidor de bomba de protons reduzem a absorcao. Orientar intervalo minimo de quatro horas.'),
  ('PROT-TRANSF-23', 1, 'Gatilho restritivo', 'A estrategia restritiva e a padrao da instituicao: transfundir com hemoglobina abaixo de 7 g/dL no paciente estavel. Hemoglobina abaixo de 7 g/dL e resultado critico e exige avaliacao medica imediata.'),
  ('PROT-TRANSF-23', 2, 'Excecoes', 'Sindrome coronariana aguda e sangramento ativo com instabilidade admitem gatilho de 8 g/dL.'),
  ('PROT-TRANSF-23', 3, 'Unidade a unidade', 'Transfundir uma unidade por vez e reavaliar a hemoglobina e a clinica antes de indicar a seguinte.'),
  ('PROT-TRANSF-23', 4, 'Registro', 'Toda transfusao exige indicacao, valor de hemoglobina pre-transfusional e consentimento registrados em prontuario.');

SELECT setval(pg_get_serial_sequence('knowledge.trechos', 'id'),
              COALESCE((SELECT MAX(id) FROM knowledge.trechos), 1));